title: RDAP.ORG
email: feedback@rdap.org
description: RDAP Response Validator
baseurl: "/"
url: "https://validator.rdap.org"
keywords: rdap, whois, rdap, domain name, dns, ip address

exclude:
  - .dockerignore
  - .gitignore
  - CNAME
  - Dockerfile
  - LICENSE
  - README.md
  - bin
  - package-lock.json
  - package.json
