name: Generate pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: create site directory
        run: cp -Rvp www _site

      - name: copy libs
        run: cp -Rvp lib _site/

      - name: configure
        uses: actions/configure-pages@v4

      - name: upload
        uses: actions/upload-pages-artifact@v3

      - name: deploy
        uses: actions/deploy-pages@v4
